export default function (state=[],action) {
    return [
        {
            "_id": "594ffbc65e07e5211a1168b8",
            "index": 0,
            "guid": "4330ecca-57df-4892-b8bc-5c9b920afc35",
            "isActive": true,
            "balance": "$3,648.02",
            "picture": "http://placehold.it/32x32",
            "age": 39,
            "eyeColor": "green",
            "name": "Darlene Russo",
            "gender": "female",
            "company": "JAMNATION",
            "email": "darlenerusso@jamnation.com",
            "phone": "+1 (935) 575-3851",
            "address": "267 Quay Street, Condon, Nebraska, 4882",
            "about": "Esse sit quis excepteur dolor cillum esse. Pariatur occaecat sint Lorem commodo irure enim dolore esse sunt sit adipisicing Lorem occaecat. Incididunt esse ipsum excepteur aute in occaecat nulla irure. Consequat labore veniam ad do ut aliquip. Mollit anim labore proident labore consectetur exercitation ea sunt. Reprehenderit esse qui occaecat fugiat officia pariatur nulla irure irure culpa commodo ad incididunt.\r\n",
            "registered": "2016-06-23T11:51:00 -04:00",
            "latitude": 8.126026,
            "longitude": -85.989969
        },
        {
            "_id": "594ffbc6c04d4797247b980c",
            "index": 1,
            "guid": "59a44cfd-7a25-44a9-b1a3-40fda570c4f7",
            "isActive": true,
            "balance": "$1,038.28",
            "picture": "http://placehold.it/32x32",
            "age": 21,
            "eyeColor": "brown",
            "name": "Megan Barker",
            "gender": "female",
            "company": "REALYSIS",
            "email": "meganbarker@realysis.com",
            "phone": "+1 (955) 525-2668",
            "address": "788 School Lane, Northchase, Missouri, 2445",
            "about": "Laboris ad ex laboris minim nostrud laborum est minim dolore. Laboris adipisicing magna quis officia laborum dolore ut esse ea excepteur exercitation commodo. Amet velit dolor exercitation adipisicing culpa consequat ea exercitation eiusmod aute. Duis consequat elit proident dolor sint aliquip nostrud Lorem consectetur ullamco enim id adipisicing. Lorem mollit consequat aute ea aliqua ipsum pariatur consectetur et aute cupidatat irure esse culpa.\r\n",
            "registered": "2014-07-12T09:12:31 -04:00",
            "latitude": 69.987053,
            "longitude": 79.223103
        },
        {
            "_id": "594ffbc61c5e86e0675b7dae",
            "index": 2,
            "guid": "a12d1f63-39b4-4554-98cd-0ad9b2001257",
            "isActive": false,
            "balance": "$1,261.59",
            "picture": "http://placehold.it/32x32",
            "age": 27,
            "eyeColor": "blue",
            "name": "Bullock Best",
            "gender": "male",
            "company": "OPTICALL",
            "email": "bullockbest@opticall.com",
            "phone": "+1 (986) 461-3030",
            "address": "696 Jamison Lane, Umapine, Palau, 2794",
            "about": "Sunt laborum nisi eiusmod sit velit. Elit non consequat ad ea consectetur proident. Lorem ut culpa nulla ex id sit sit sint mollit velit. Nostrud officia anim sint proident. Nisi ad sit aliquip do enim dolor fugiat dolor qui non. Non quis voluptate exercitation in velit est commodo commodo consectetur proident deserunt dolor.\r\n",
            "registered": "2015-01-17T01:48:54 -04:00",
            "latitude": -25.378147,
            "longitude": 62.872765
        },
        {
            "_id": "594ffbc642ab3081c6332273",
            "index": 3,
            "guid": "6eb5fbe7-433d-4bf9-80dd-615b153bfed7",
            "isActive": true,
            "balance": "$1,846.46",
            "picture": "http://placehold.it/32x32",
            "age": 25,
            "eyeColor": "brown",
            "name": "Tracie Moss",
            "gender": "female",
            "company": "PLEXIA",
            "email": "traciemoss@plexia.com",
            "phone": "+1 (852) 563-2473",
            "address": "923 Clove Road, Lavalette, Kansas, 5417",
            "about": "Aute magna laboris tempor in proident veniam culpa. Do enim pariatur cillum elit consectetur laborum enim ex adipisicing aliquip. Nisi incididunt fugiat duis eu sit dolor qui qui eu adipisicing amet. Exercitation veniam est ut enim sit. Aute quis consequat aute duis voluptate. Dolor dolore deserunt occaecat quis consectetur cillum deserunt in culpa.\r\n",
            "registered": "2015-08-30T06:50:06 -04:00",
            "latitude": 5.177473,
            "longitude": 99.586139
        },
        {
            "_id": "594ffbc6e7ff73bbbe5fe2ed",
            "index": 4,
            "guid": "b9c4adc2-7da9-4587-884e-1ee39df9807c",
            "isActive": true,
            "balance": "$1,110.64",
            "picture": "http://placehold.it/32x32",
            "age": 37,
            "eyeColor": "green",
            "name": "Janie Cabrera",
            "gender": "female",
            "company": "AQUAMATE",
            "email": "janiecabrera@aquamate.com",
            "phone": "+1 (801) 581-2958",
            "address": "434 Ivan Court, Newry, Nevada, 4946",
            "about": "Adipisicing laborum id minim reprehenderit dolor cupidatat enim. Elit pariatur reprehenderit ex cillum consequat cillum eiusmod id velit cupidatat excepteur. Officia incididunt mollit minim exercitation nulla tempor elit ipsum duis amet tempor. Quis officia Lorem ea laborum proident tempor laboris veniam aliquip non deserunt aliqua. Sunt velit Lorem minim cupidatat esse labore sint veniam. Excepteur mollit nostrud non laborum.\r\n",
            "registered": "2015-08-20T05:07:40 -04:00",
            "latitude": 23.639622,
            "longitude": 56.518284
        },
        {
            "_id": "594ffbc6d426d9d66a862ba0",
            "index": 5,
            "guid": "4fbd4ed2-7b27-4160-b813-73573496e849",
            "isActive": true,
            "balance": "$2,338.12",
            "picture": "http://placehold.it/32x32",
            "age": 27,
            "eyeColor": "blue",
            "name": "Alice Lane",
            "gender": "female",
            "company": "STRALUM",
            "email": "alicelane@stralum.com",
            "phone": "+1 (881) 449-3226",
            "address": "609 Mill Lane, Cawood, Utah, 8127",
            "about": "Nisi labore mollit elit dolor elit. Nulla deserunt in veniam adipisicing anim aliqua. Adipisicing deserunt cillum magna excepteur tempor pariatur eu quis. Ut anim pariatur incididunt ea enim sint laborum eu laborum fugiat reprehenderit proident officia consectetur. Ex exercitation anim aute ipsum nisi sunt Lorem voluptate anim voluptate. Fugiat est Lorem magna eu officia voluptate aliquip velit aliqua nostrud.\r\n",
            "registered": "2017-03-18T02:39:26 -04:00",
            "latitude": -4.60612,
            "longitude": 130.264669
        },
        {
            "_id": "594ffbc6a5f95c71bd181c42",
            "index": 6,
            "guid": "6f391867-6d4d-43ae-b2b7-5bcedf90becd",
            "isActive": true,
            "balance": "$3,566.46",
            "picture": "http://placehold.it/32x32",
            "age": 22,
            "eyeColor": "blue",
            "name": "Alexandria Owens",
            "gender": "female",
            "company": "TELEPARK",
            "email": "alexandriaowens@telepark.com",
            "phone": "+1 (907) 442-3321",
            "address": "119 Troy Avenue, Westphalia, Pennsylvania, 6437",
            "about": "Exercitation ullamco velit irure occaecat veniam officia Lorem esse ut ex sit dolor. Ut amet ea sint ipsum deserunt sit velit enim labore mollit eiusmod. Culpa sint duis sint tempor occaecat exercitation fugiat velit. Exercitation est ea enim eiusmod non consequat excepteur ex. Esse laborum est mollit sunt consectetur anim laborum quis. Ullamco exercitation fugiat nostrud occaecat ut in elit occaecat.\r\n",
            "registered": "2015-04-28T01:42:01 -04:00",
            "latitude": 64.407945,
            "longitude": 126.742203
        }
    ]
}